name: Bug Report
description: Something isn't working as it should
labels: "bug"

body:
  - type: textarea
    attributes:
      label: Describe the problem
      description: add expected and actual result if it's not blatantly obvious
  - type: textarea
    attributes:
      label: Gist to reproduce
      description: >
        Full source code is appreciated. We also very much appreciate
        it if you try to narrow the source down to a small stand-alone example.
      render: python
  - type: dropdown
    attributes:
      label: Severity
      description: How does this affect you?
      options:
        - annoying but workaround is available
        - annoying but i can live with it
        - blocker (literally unusable)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Your Environment
      description: include any relevant information such as operating system and the output of `mypy --version`
