name: Publish documentation

on:
  workflow_dispatch:

jobs:
  docs:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest
    env:
      TOXENV: docs
      TOX_SKIP_MISSING_INTERPRETERS: False
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install tox
        run: pip install --upgrade 'setuptools!=50' tox==4.11.0
      - name: Setup tox environment
        run: tox run -e ${{ env.TOXENV }} --notest
      - name: Test
        run: tox run -e ${{ env.TOXENV }} --skip-pkg-install
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ".tox/docs_out"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
