name: Publish

on:
  release:

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        shell: bash
        run: |
          version=$(python -c "import mypy.version; print(mypy.version.__based_version__)")
          python misc/upload-pypi.py $version

      # Upload wheels as a release asset
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./dist/*

  docs:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest
    env:
      TOXENV: docs
      TOX_SKIP_MISSING_INTERPRETERS: False
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install tox
        run: pip install --upgrade 'setuptools!=50' tox==4.11.0
      - name: Setup tox environment
        run: tox run -e ${{ env.TOXENV }} --notest
      - name: Test
        run: tox run -e ${{ env.TOXENV }} --skip-pkg-install
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ".tox/docs_out"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
